# Primary database (H2)
spring.datasource.url=jdbc:h2:file:./db/transactions.db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=10

# Secondary database (PostgreSQL)
spring.second-datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/rules
spring.second-datasource.hikari.username=manager
spring.second-datasource.hikari.password=123
spring.second-datasource.hikari.driver-class-name=org.postgresql.Driver
spring.second-datasource.hikari.maximum-pool-size=10
spring.jpa.hibernate.ddl-auto=update


# Liquibase
spring.liquibase.enabled=true
spring.liquibase.url=jdbc:postgresql://localhost:5432/rules
spring.liquibase.user=manager
spring.liquibase.password=123
spring.liquibase.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.contexts=second-db
spring.liquibase.default-schema=public
spring.liquibase.drop-first=true

logging.level.org.springframework=INFO
logging.level.liquibase=INFO

telegram.bot.token=7803716085:AAG3hWZN98Is-V5yo_IYqy9ct7xDCsYvu2s
telegram.bot.username=StarBankUserBot